services:
  mysql:
    container_name: 'bozo-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=first-spring-crud'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'